apiVersion: batch/v1
kind: CronJob
metadata:
  name: api_cache_worker
  namespace: api
  labels:
    app: api_cache_worker
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: api_cache_worker
            image: eu.gcr.io/serlo-shared/api-cache-worker 
            env:
            - name: API_HOST
              value: 'string'
            - name: SECRET
              value: 'string'
            - name: SERVICE
              value: 'string'
            - name: PAGINATION
              value: 'string'
          restartPolicy: Never
